In [18]:
import pandas as pd
import numpy as np
import plotly.express as px

ELIMINATION_RATE = 0.0055
SIMULATION_TIME = 60 * 24
CONCENTRATION_MIN = 200
CONCENTRATION_MAX = 600

def simulate(initial_concentration, concentration, time_between_doses):
    data = []
    concentration_with_increment = concentration

    for i in range(0, SIMULATION_TIME + 1):
        if i == 0:
            concentration_with_increment = initial_concentration
        
        data.append([concentration_with_increment])
        concentration_with_increment *= 1 - ELIMINATION_RATE
        if i % time_between_doses == 0 and i != 0:
            concentration_with_increment += concentration

    data = np.array(data)
    df = pd.DataFrame(data, columns=[f"Concentración con incremento cada {time_between_doses} min (mg/L)"])
    display(df)
    
    fig = px.line(df, title="Concentración de medicamento a lo largo del tiempo")
    fig.update_layout(xaxis_title="Tiempo (min)", yaxis_title="Concentración (mg/L)")
    fig.add_hline(y=CONCENTRATION_MIN, line_dash="dash", line_color="red", annotation_text="Concentración mínima (200 mg/L)")
    fig.add_hline(y=CONCENTRATION_MAX, line_dash="dash", line_color="red", annotation_text="Concentración máxima (600 mg/L)")
    fig.show()

## SIMULACIÓN A

In [19]:
CONCENTRATION = 425
INITIAL_CONCENTRATION = CONCENTRATION
TIME_BETWEEN_DOSES = 60 * 4 # cada 4 horas
simulate(INITIAL_CONCENTRATION, CONCENTRATION, TIME_BETWEEN_DOSES)

      Concentración con incremento cada 240 min (mg/L)
0                                           425.000000
1                                           422.662500
2                                           420.337856
3                                           418.025998
4                                           415.726855
...                                                ...
1436                                        158.401056
1437                                        157.529850
1438                                        156.663436
1439                                        155.801787
1440                                        154.944877

[1441 rows x 1 columns]

## SIMULACIÓN B (PROPUESTA)

In [20]:
CONCENTRATION = 365
INITIAL_CONCENTRATION = 570
TIME_BETWEEN_DOSES = 60 * 3 # cada 3 horas
simulate(INITIAL_CONCENTRATION, CONCENTRATION, TIME_BETWEEN_DOSES)

      Concentración con incremento cada 180 min (mg/L)
0                                           570.000000
1                                           566.865000
2                                           563.747243
3                                           560.646633
4                                           557.563076
...                                                ...
1436                                        220.886343
1437                                        219.671468
1438                                        218.463275
1439                                        217.261727
1440                                        216.066787

[1441 rows x 1 columns]